# Generated by Django 4.1.7 on 2023-03-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
