# Generated by Django 4.1.7 on 2023-03-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0002_run_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="runner",
            name="user",
        ),
        migrations.AddField(
            model_name="runner",
            name="src_username",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="mission",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="run",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="runner",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="runner",
            name="tsc_username",
            field=models.TextField(blank=True),
        ),
    ]
