# Generated by Django 4.1.7 on 2024-03-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_runner_points_m1_runner_points_m2_runner_points_m3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='is_boss',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='runner',
            name='points_boss',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mission',
            name='level',
            field=models.CharField(choices=[('CE', 'City Escape'), ('WC', 'Wild Canyon'), ('PL', 'Prison Lane'), ('MHA', 'Metal Harbor'), ('GF', 'Green Forest'), ('PH', 'Pumpkin Hill'), ('MST', 'Mission Street'), ('AM', 'Aquatic Mine'), ('101', 'Route 101'), ('HB', 'Hidden Base'), ('PC', 'Pyramid Cave'), ('DC', 'Death Chamber'), ('EE', 'Eternal Engine'), ('MHE', 'Meteor Herd'), ('CG', 'Crazy Gadget'), ('FR', 'Final Rush'), ('IG', 'Iron Gate'), ('DL', 'Dry Lagoon'), ('SO', 'Sand Ocean'), ('RH', 'Radical Highway'), ('EQ', 'Egg Quarters'), ('LC', 'Lost Colony'), ('WB', 'Weapons Bed'), ('SH', 'Security Hall'), ('WJ', 'White Jungle'), ('280', 'Route 280'), ('SR', 'Sky Rail'), ('MSP', 'Mad Space'), ('CW', 'Cosmic Wall'), ('FC', 'Final Chase'), ('CC', "Cannon's Core"), ('GH', 'Green Hill'), ('BF', 'Big Foot'), ('EGG1', 'Eggman 1'), ('SH1', 'Shadow 1'), ('KBB', 'King Boom Boo'), ('EGH', 'Egg Golem (Hero)'), ('RG', 'Rouge'), ('EGG2', 'Eggman 2'), ('SH2', 'Shadow 2'), ('HS', 'Hot Shot'), ('T1', 'Tails 1'), ('FD', 'Flying Dog'), ('SO1', 'Sonic 1'), ('KN', 'Knuckles'), ('T2', 'Tails 2'), ('SO2', 'Sonic 2')], default='GH', max_length=4),
        ),
    ]
